package telegram

import (
	"context"
	"fmt"
	"sync"

	billingsvc "streampass/backend/internal/application/billing"
)

// Provider implements billing.PaymentProvider using Telegram Stars invoices.
// FetchPaymentStatus returns Pending until ActivateCharge marks a charge succeeded
// (Telegram has no reliable poll API for Stars; webhook is the source of truth).
type Provider struct {
	bot *Client
	mu  sync.Mutex
	// succeeded charge ids recorded by webhook for FetchPaymentStatus.
	succeeded map[string]struct{}
	plans     map[string]StarsPlan
}

// StarsPlan is a Stars-priced tariff.
type StarsPlan struct {
	Code       string
	Title      string
	Stars      int
	PeriodDays int
}

// DefaultStarsPlans matches TZ 02.3.
func DefaultStarsPlans() []StarsPlan {
	return []StarsPlan{
		{Code: "month", Title: "1 месяц", Stars: 499, PeriodDays: 30},
		{Code: "quarter", Title: "3 месяца", Stars: 1299, PeriodDays: 90},
		{Code: "year", Title: "12 месяцев", Stars: 3999, PeriodDays: 365},
	}
}

// NewProvider builds a Stars PaymentProvider.
func NewProvider(bot *Client, plans []StarsPlan) *Provider {
	m := make(map[string]StarsPlan, len(plans))
	for _, p := range plans {
		m[p.Code] = p
	}
	return &Provider{bot: bot, succeeded: map[string]struct{}{}, plans: m}
}

// CreatePayment ignores amountRUB and uses description as "StreamPass <Title>"
// plus providerPaymentID as invoice payload. amountRUB is reinterpreted as Stars
// when > 0 and matching a known plan via description suffix — callers should pass
// Stars amount in amountRUB for Telegram mode.
func (p *Provider) CreatePayment(ctx context.Context, userID string, amountRUB int64, description string) (string, string, error) {
	if p.bot == nil || !p.bot.Enabled() {
		return "", "", fmt.Errorf("telegram payments not configured (TELEGRAM_BOT_TOKEN)")
	}
	stars := int(amountRUB)
	if stars <= 0 {
		stars = 499
	}
	title := description
	if title == "" {
		title = "StreamPass"
	}
	// providerPaymentID is generated by billing service as our payment row id —
	// but CreatePayment is called BEFORE insert. Billing uses returned ID.
	// We generate payload after billing creates payment — so billing must pass
	// payload. Current billing flow: provider creates ID, then we store it.
	// For Telegram we use a provisional id from amount+user in description.
	// Better: billing service creates payment id first. We'll adjust billing.
	payload := fmt.Sprintf("pending:%s:%d", userID, stars)
	link, err := p.bot.CreateInvoiceLink(ctx, title, description, payload, stars)
	if err != nil {
		return "", "", err
	}
	return payload, link, nil
}

// FetchPaymentStatus returns Succeeded only after MarkSucceededCharge.
func (p *Provider) FetchPaymentStatus(_ context.Context, providerPaymentID string) (billingsvc.PaymentStatus, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	if _, ok := p.succeeded[providerPaymentID]; ok {
		return billingsvc.PaymentStatusSucceeded, nil
	}
	return billingsvc.PaymentStatusPending, nil
}

// MarkSucceededCharge records that Telegram confirmed a charge (for FetchPaymentStatus).
func (p *Provider) MarkSucceededCharge(providerPaymentID string) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.succeeded[providerPaymentID] = struct{}{}
}

// CreateInvoiceForPayment creates an invoice whose payload is the payment row id.
func (p *Provider) CreateInvoiceForPayment(ctx context.Context, paymentID, planCode string) (string, int, int, string, error) {
	plan, ok := p.plans[planCode]
	if !ok {
		plan, ok = p.plans["month"]
		if !ok {
			return "", 0, 0, "", fmt.Errorf("no telegram plans configured")
		}
	}
	if p.bot == nil || !p.bot.Enabled() {
		return "", 0, 0, "", fmt.Errorf("telegram payments not configured (TELEGRAM_BOT_TOKEN)")
	}
	title := "StreamPass — " + plan.Title
	desc := fmt.Sprintf("Подписка StreamPass (%s)", plan.Title)
	link, err := p.bot.CreateInvoiceLink(ctx, title, desc, paymentID, plan.Stars)
	return link, plan.Stars, plan.PeriodDays, plan.Title, err
}

// Bot exposes the underlying client for messaging / pre-checkout.
func (p *Provider) Bot() *Client { return p.bot }

var _ billingsvc.PaymentProvider = (*Provider)(nil)
