package com.streampass.app

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.net.NetworkRequest
import android.net.VpnService
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.os.ParcelFileDescriptor
import android.util.Log
import androidx.core.app.NotificationCompat
import io.flutter.plugin.common.EventChannel
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import java.util.concurrent.atomic.AtomicBoolean

// import streampasscore.Streampasscore  // <- generated by `gomobile bind`
// See go_core/README.md for how this AAR is produced from the shared
// Go core (Decision Engine + Rule Engine + Hysteria2 client).

class StreamPassVpnService : VpnService() {

    companion object {
        private const val TAG = "StreamPassVpn"
        var eventSink: EventChannel.EventSink? = null
        private var instance: StreamPassVpnService? = null

        @Volatile
        var lastEvent: String = "disconnected"
        @Volatile
        var lastRelay: String? = null
        @Volatile
        var lastPingMs: Int? = null
        @Volatile
        var lastError: String? = null

        private const val ACTION_CONNECT = "com.streampass.app.CONNECT"
        private const val ACTION_DISCONNECT = "com.streampass.app.DISCONNECT"
        private const val NOTIFICATION_CHANNEL_ID = "streampass_vpn_status"
        private const val FAILURE_CHANNEL_ID = "streampass_vpn_failures"
        private const val NOTIFICATION_ID = 1
        private const val FAILURE_NOTIFICATION_ID = 2

        @Volatile
        private var userRequestedStop = false

        fun start(context: Context, args: Map<*, *>?) {
            userRequestedStop = false
            ConnectLogger.log(context, "VpnService.start id=${args?.get("id")} host=${args?.get("host")}")
            val intent = Intent(context, StreamPassVpnService::class.java).apply {
                action = ACTION_CONNECT
                putExtra("id", args?.get("id") as? String ?: "")
                putExtra("host", args?.get("host") as? String ?: "")
                putExtra("port", (args?.get("port") as? Int) ?: 443)
                putExtra("displayName", args?.get("displayName") as? String ?: "")
                putExtra("connectionConfig", args?.get("connectionConfig") as? String ?: "")
                putExtra("rulesJson", args?.get("rulesJson") as? String ?: "")
                putExtra("exclusionsJson", args?.get("exclusionsJson") as? String ?: "[]")
                putExtra("bypassPackagesJson", args?.get("bypassPackagesJson") as? String ?: "[]")
                putExtra("networkMode", args?.get("networkMode") as? String ?: "split")
                putExtra("mtu", (args?.get("mtu") as? Int) ?: 1400)
                putExtra("blockUdp443", (args?.get("blockUdp443") as? Boolean) ?: false)
                putExtra("optionsJson", args?.get("optionsJson") as? String ?: "")
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.startForegroundService(intent)
            } else {
                context.startService(intent)
            }
        }

        fun stop(context: Context) {
            userRequestedStop = true
            val svc = instance
            if (svc != null) {
                svc.tearDown()
            } else {
                context.startService(Intent(context, StreamPassVpnService::class.java).apply {
                    action = ACTION_DISCONNECT
                })
            }
        }

        fun updateRules(rulesJson: String, exclusionsJson: String): String {
            val bridge = instance?.tunnelBridge
            return bridge?.updateRules(rulesJson, exclusionsJson)
                ?: "no active tunnel"
        }

        /** Snapshot for Flutter MethodChannel getStatus (AUDIT-003 BUG-004). */
        fun statusSnapshot(): Map<String, Any?> = mapOf(
            "event" to lastEvent,
            "relay" to lastRelay,
            "pingMs" to lastPingMs,
            "error" to lastError,
            "active" to (instance != null && lastEvent == "connected"),
        )
    }

    private var tunInterface: ParcelFileDescriptor? = null
    private var tunnelBridge: TunnelBridge? = null
    private val scope = CoroutineScope(Dispatchers.IO + Job())
    private val mainHandler = Handler(Looper.getMainLooper())
    private val teardownLock = Any()
    @Volatile private var tornDown = false

    private var relayId: String = ""
    private var relayHost: String = ""
    private var relayPort: Int = 443
    private var relayDisplayName: String = ""
    private var connectionConfig: String = ""
    private var rulesJson: String = ""
    private var exclusionsJson: String = "[]"
    private var bypassPackagesJson: String = "[]"
    private var networkMode: String = "split"
    private var mtu: Int = 1400
    private var blockUdp443: Boolean = false
    private var optionsJson: String = ""
    private var networkCallback: ConnectivityManager.NetworkCallback? = null
    private val networkRecoverInFlight = AtomicBoolean(false)
    private var lastValidatedNetwork: Network? = null

    override fun onCreate() {
        super.onCreate()
        instance = this
        tornDown = false
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_DISCONNECT) {
            userRequestedStop = true
            tearDown()
            return START_NOT_STICKY
        }
        if (intent?.action == ACTION_CONNECT) {
            synchronized(teardownLock) { tornDown = false }
            relayId = intent.getStringExtra("id") ?: ""
            relayHost = intent.getStringExtra("host") ?: ""
            relayPort = intent.getIntExtra("port", 443)
            relayDisplayName = intent.getStringExtra("displayName") ?: ""
            connectionConfig = intent.getStringExtra("connectionConfig") ?: ""
            rulesJson = intent.getStringExtra("rulesJson") ?: ""
            exclusionsJson = intent.getStringExtra("exclusionsJson") ?: "[]"
            bypassPackagesJson = intent.getStringExtra("bypassPackagesJson") ?: "[]"
            networkMode = intent.getStringExtra("networkMode") ?: "split"
            mtu = intent.getIntExtra("mtu", 1400).coerceIn(1200, 1500)
            blockUdp443 = intent.getBooleanExtra("blockUdp443", false)
            optionsJson = intent.getStringExtra("optionsJson") ?: ""
            if (optionsJson.isBlank()) {
                // Build options for Go StartTunnel (networkMode / mtu / blockUdp443).
                val block = blockUdp443 || networkMode == "tcp_only"
                optionsJson =
                    """{"networkMode":"$networkMode","mtu":$mtu,"blockUdp443":$block}"""
            }

            ConnectLogger.clear(this)
            Log.i(TAG, "connect relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length}")
            ConnectLogger.log(
                this,
                "=== connect session begin === onStartCommand relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length} rulesLen=${rulesJson.length} networkMode=$networkMode mtu=$mtu blockUdp443=$blockUdp443",
            )
            startForeground(NOTIFICATION_ID, buildNotification("Подключение…"))
            emit("connecting")
            scope.launch { establishTunnel() }
        }
        return START_STICKY
    }

    private fun ensureFailureChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            val channel = NotificationChannel(
                FAILURE_CHANNEL_ID,
                "Сбои соединения",
                NotificationManager.IMPORTANCE_DEFAULT,
            ).apply { description = "Уведомления при обрыве StreamPass" }
            manager.createNotificationChannel(channel)
        }
    }

    private fun openAppPendingIntent(): PendingIntent {
        val intent = Intent(this, MainActivity::class.java).apply {
            action = Intent.ACTION_MAIN
            addCategory(Intent.CATEGORY_LAUNCHER)
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or
                Intent.FLAG_ACTIVITY_SINGLE_TOP or
                Intent.FLAG_ACTIVITY_CLEAR_TOP
        }
        val flags = PendingIntent.FLAG_UPDATE_CURRENT or
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                PendingIntent.FLAG_IMMUTABLE
            } else {
                0
            }
        return PendingIntent.getActivity(this, 0, intent, flags)
    }

    private fun notifyFailure(message: String) {
        if (userRequestedStop) return
        if (!NativeSettingsChannel.failureNotificationsEnabled(this)) return
        ensureFailureChannel()
        val text = message.ifBlank { "Соединение прервано" }
        val notification = NotificationCompat.Builder(this, FAILURE_CHANNEL_ID)
            .setContentTitle("StreamPass")
            .setContentText(text)
            .setSmallIcon(android.R.drawable.stat_sys_warning)
            .setContentIntent(openAppPendingIntent())
            .setAutoCancel(true)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .build()
        getSystemService(NotificationManager::class.java)
            .notify(FAILURE_NOTIFICATION_ID, notification)
    }

    private fun buildNotification(status: String): Notification {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            val channel = NotificationChannel(
                NOTIFICATION_CHANNEL_ID,
                "StreamPass",
                NotificationManager.IMPORTANCE_LOW,
            ).apply { description = "Статус соединения StreamPass" }
            manager.createNotificationChannel(channel)
        }

        return NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
            .setContentTitle("StreamPass")
            .setContentText(status)
            .setSmallIcon(android.R.drawable.stat_sys_download_done) // заменить на брендовую иконку
            .setContentIntent(openAppPendingIntent())
            .setOngoing(true)
            .setOnlyAlertOnce(true)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    private fun updateNotification(status: String) {
        val manager = getSystemService(NotificationManager::class.java)
        manager.notify(NOTIFICATION_ID, buildNotification(status))
    }

    private suspend fun establishTunnel() {
        try {
            if (tornDown) return
            if (relayHost.isEmpty()) {
                throw IllegalStateException("No relay host provided — was GET /servers called first?")
            }
            val verLabel = try {
                val pi = packageManager.getPackageInfo(packageName, 0)
                val vc = if (android.os.Build.VERSION.SDK_INT >= 28) pi.longVersionCode else @Suppress("DEPRECATION") pi.versionCode.toLong()
                "${pi.versionName}+$vc"
            } catch (_: Throwable) {
                "unknown"
            }
            ConnectLogger.log(this, "connect-flow=v2-prepare-first build=$verLabel routing-policy-v1")
            ConnectLogger.log(this, "establishTunnel: validating connection_config")
            if (connectionConfig.isBlank()) {
                throw IllegalStateException("connection_config is empty — relay misconfigured in backend")
            }
            if (!connectionConfig.startsWith("hysteria2://") && !connectionConfig.startsWith("hy2://")) {
                // Do not log URI prefix — may contain user:password@ before host.
                val scheme = connectionConfig.substringBefore(':', missingDelimiterValue = "none")
                throw IllegalStateException("connection_config must be hysteria2:// or hy2:// URI (got scheme=$scheme)")
            }

            val bridge = TunnelBridge(this) { event, relay, pingMs, error ->
                ConnectLogger.log(this@StreamPassVpnService, "tunnel event=$event relay=$relay error=$error pingMs=$pingMs")
                Log.i(TAG, "tunnel event=$event relay=$relay error=$error")
                emit(event, relay = relay ?: relayDisplayName.ifEmpty { relayHost }, pingMs = pingMs, error = error)
                if (event == "error") {
                    Handler(Looper.getMainLooper()).post { tearDown() }
                }
            }
            tunnelBridge = bridge

            // Protect underlay sockets BEFORE PrepareRelay so QUIC survives TUN default route.
            bridge.setEventLogger { msg -> ConnectLogger.log(this@StreamPassVpnService, msg) }
            bridge.setSocketProtector { fd ->
                val ok = protect(fd)
                ConnectLogger.log(this@StreamPassVpnService, "protect(fd=$fd)=$ok")
                ok
            }

            // Hysteria handshake MUST complete before TUN default route is added,
            // otherwise QUIC packets to the relay loop into the empty interface.
            ConnectLogger.log(this, "PrepareRelay before TUN (relay=$relayHost:$relayPort)")
            val prepareErr = bridge.prepareRelay(relayHost, relayPort, connectionConfig)
            if (tornDown) return
            if (prepareErr != null) {
                throw IllegalStateException(prepareErr)
            }
            ConnectLogger.log(this, "PrepareRelay OK, establishing TUN")

            if (tornDown) {
                bridge.stopTunnel()
                return
            }

            // DNS must be a routed fake address (NOT the TUN iface IP). On One UI,
            // addDnsServer(10.10.0.1) hairpins locally → queries never enter TUN →
            // Chrome "can't find IP" while VPN shows Connected. 198.18.0.1 is
            // captured by 0.0.0.0/0; Go hijacks any *:53 (UDP+TCP).
            val vpnDns = "198.18.0.1"
            val vpnBuilder = Builder()
                .setSession("StreamPass")
                .addAddress("10.10.0.1", 30)
                .addDnsServer(vpnDns)
                .setMtu(mtu)
            // Avoid OEM "metered VPN" throttling / captive-portal weirdness.
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
                vpnBuilder.setMetered(false)
            }
            // Do NOT allowFamily(AF_INET6): on One UI / Chrome Secure DNS, AAAA leaks
            // make apps dial IPv6 on the underlay (outside VPN) → sites hang while
            // Hysteria sees zero streams. Keep IPv6 in TUN; Go drops it (+40) and
            // DNS suppresses AAAA so apps use IPv4 via the tunnel.
            ConnectLogger.log(this, "ipv6=capture (no allowFamily; drop+aaaa-suppress in Go)")
            val routeInfo = VpnRouteConfigurator.apply(vpnBuilder, assets, networkMode)
            val extraBypass = parseBypassPackages(bypassPackagesJson)
            val bypassCount = VpnBypassApps.apply(vpnBuilder, packageManager, packageName, extraBypass)
            ConnectLogger.log(this, "vpn dns=$vpnDns (Go dnscache hijack *:53) networkMode=$networkMode mtu=$mtu")
            ConnectLogger.log(this, "split-tunnel mode=${routeInfo.mode} routes=${routeInfo.routeCount} ruExcludes=${routeInfo.excludeCount} appBypass=$bypassCount extraUser=${extraBypass.size}")
            tunInterface = vpnBuilder.establish()

            val fd = tunInterface?.fd
                ?: throw IllegalStateException("VPN interface could not be established")
            ConnectLogger.log(this, "TUN established fd=$fd mtu=$mtu addr=10.10.0.1/30 dns=$vpnDns options=$optionsJson")
            if (tornDown) {
                tunInterface?.close()
                tunInterface = null
                bridge.stopTunnel()
                return
            }

            bridge.startTunnel(fd, relayHost, relayPort, connectionConfig, rulesJson, exclusionsJson, optionsJson)
            registerNetworkCallback()
        } catch (e: Exception) {
            if (tornDown) return
            Log.e(TAG, "establishTunnel failed", e)
            ConnectLogger.log(this, "establishTunnel failed: ${e.message}")
            emit("error", error = e.message ?: "unknown error")
            tearDown()
        }
    }

    /** Issue #2: Wi-Fi ↔ LTE — invalidate underlay and rehandshake without tearing TUN. */
    private fun registerNetworkCallback() {
        unregisterNetworkCallback()
        val cm = getSystemService(ConnectivityManager::class.java) ?: return
        val request = NetworkRequest.Builder()
            .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .build()
        val cb = object : ConnectivityManager.NetworkCallback() {
            override fun onAvailable(network: Network) {
                maybeRecoverOnNetworkChange(network, "available")
            }

            override fun onCapabilitiesChanged(network: Network, caps: NetworkCapabilities) {
                if (caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)) {
                    maybeRecoverOnNetworkChange(network, "validated")
                }
            }

            override fun onLost(network: Network) {
                ConnectLogger.log(this@StreamPassVpnService, "[lifecycle] underlay lost network=$network")
            }
        }
        networkCallback = cb
        try {
            cm.registerNetworkCallback(request, cb)
            ConnectLogger.log(this, "[lifecycle] NetworkCallback registered")
        } catch (t: Throwable) {
            Log.w(TAG, "registerNetworkCallback failed", t)
            networkCallback = null
        }
    }

    private fun unregisterNetworkCallback() {
        val cb = networkCallback ?: return
        networkCallback = null
        try {
            getSystemService(ConnectivityManager::class.java)?.unregisterNetworkCallback(cb)
        } catch (_: Throwable) {
        }
    }

    private fun maybeRecoverOnNetworkChange(network: Network, reason: String) {
        if (tornDown || lastEvent != "connected") return
        val prev = lastValidatedNetwork
        if (prev != null && prev == network) return
        lastValidatedNetwork = network
        if (prev == null) {
            // First validated network after connect — not a change.
            ConnectLogger.log(this, "[lifecycle] underlay initial network=$network reason=$reason")
            return
        }
        if (!networkRecoverInFlight.compareAndSet(false, true)) return
        ConnectLogger.log(this, "[lifecycle] RECONNECTING underlay change prev=$prev next=$network reason=$reason")
        scope.launch {
            try {
                val bridge = tunnelBridge ?: return@launch
                val err = bridge.reconnectRelay(relayHost, relayPort, connectionConfig)
                if (err != null) {
                    ConnectLogger.log(this@StreamPassVpnService, "[lifecycle] RELAY_FAILED: $err")
                    emit("error", error = "relay_reconnect_failed: $err")
                } else {
                    ConnectLogger.log(this@StreamPassVpnService, "[lifecycle] relay reconnected after network change")
                }
            } finally {
                networkRecoverInFlight.set(false)
            }
        }
    }

    private fun releaseResources() {
        unregisterNetworkCallback()
        lastValidatedNetwork = null
        // Close TUN first so no new packets enter Go while we tear down.
        val tun = tunInterface
        tunInterface = null
        try {
            tun?.close()
        } catch (t: Throwable) {
            Log.e(TAG, "TUN close failed", t)
        }

        val bridge = tunnelBridge
        tunnelBridge = null
        try {
            bridge?.stopTunnel()
        } catch (t: Throwable) {
            Log.e(TAG, "stopTunnel failed", t)
        }
        try {
            bridge?.clearSocketProtector()
        } catch (t: Throwable) {
            Log.e(TAG, "clearSocketProtector failed", t)
        }
    }

    private fun tearDown() {
        synchronized(teardownLock) {
            if (tornDown) return
            tornDown = true
        }
        ConnectLogger.log(this, "[vpn] stop begin")
        scope.launch {
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "releaseResources failed", t)
                ConnectLogger.log(this@StreamPassVpnService, "releaseResources failed: ${t.message}")
            }
            mainHandler.post {
                try {
                    emit("disconnected")
                    ConnectLogger.log(this@StreamPassVpnService, "[vpn] stop complete")
                    stopForeground(STOP_FOREGROUND_REMOVE)
                    // Do not stopSelf() here — on some OEMs it kills the Flutter process
                    // when the user switched to Chrome/banking apps. Service stays idle until
                    // next CONNECT or process exit.
                } catch (t: Throwable) {
                    Log.e(TAG, "tearDown finalize failed", t)
                }
            }
        }
    }

    override fun onDestroy() {
        // Never call stopSelf() from onDestroy — that crashes the process
        // when Android tears down the service (e.g. after APK update).
        ConnectLogger.log(this, "onDestroy")
        if (!tornDown) {
            tornDown = true
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "onDestroy releaseResources failed", t)
            }
        }
        instance = null
        super.onDestroy()
    }

    override fun onRevoke() {
        // System revoked VPN permission (e.g. another VPN app took over).
        notifyFailure("VPN отозван системой")
        tearDown()
        super.onRevoke()
    }

    private fun emit(event: String, relay: String? = null, pingMs: Int? = null, error: String? = null) {
        lastEvent = event
        lastRelay = relay
        lastPingMs = pingMs
        lastError = error
        mainHandler.post {
            val payload = mutableMapOf<String, Any?>("event" to event)
            relay?.let { payload["relay"] = it }
            pingMs?.let { payload["pingMs"] = it }
            error?.let { payload["error"] = it }
            try {
                eventSink?.success(payload)
            } catch (t: Throwable) {
                Log.e(TAG, "eventSink failed for event=$event", t)
            }

            val statusText = when (event) {
                "connecting" -> "Подключение…"
                "connected" -> "Подключено${relay?.let { " · $it" } ?: ""}"
                "error" -> "Ошибка соединения"
                else -> "Отключено"
            }
            if (event != "disconnected") updateNotification(statusText)
            if (event == "error") {
                notifyFailure(error ?: "Ошибка соединения")
            }
        }
    }

    private fun parseBypassPackages(raw: String): List<String> {
        if (raw.isBlank() || raw == "[]") return emptyList()
        return try {
            val trimmed = raw.trim().removePrefix("[").removeSuffix("]")
            if (trimmed.isBlank()) return emptyList()
            trimmed.split(',')
                .map { it.trim().trim('"').trim('\'') }
                .filter { it.isNotEmpty() }
        } catch (_: Throwable) {
            emptyList()
        }
    }
}