package com.streampass.app

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.net.VpnService
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.os.ParcelFileDescriptor
import android.util.Log
import androidx.core.app.NotificationCompat
import io.flutter.plugin.common.EventChannel
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

// import streampasscore.Streampasscore  // <- generated by `gomobile bind`
// See go_core/README.md for how this AAR is produced from the shared
// Go core (Decision Engine + Rule Engine + Hysteria2 client).

class StreamPassVpnService : VpnService() {

    companion object {
        private const val TAG = "StreamPassVpn"
        var eventSink: EventChannel.EventSink? = null
        private var instance: StreamPassVpnService? = null

        private const val ACTION_CONNECT = "com.streampass.app.CONNECT"
        private const val NOTIFICATION_CHANNEL_ID = "streampass_vpn_status"
        private const val NOTIFICATION_ID = 1

        fun start(context: Context, args: Map<*, *>?) {
            ConnectLogger.clear(context)
            ConnectLogger.log(context, "VpnService.start id=${args?.get("id")} host=${args?.get("host")}")
            context.startService(Intent(context, StreamPassVpnService::class.java).apply {
                action = ACTION_CONNECT
                putExtra("id", args?.get("id") as? String ?: "")
                putExtra("host", args?.get("host") as? String ?: "")
                putExtra("port", (args?.get("port") as? Int) ?: 443)
                putExtra("displayName", args?.get("displayName") as? String ?: "")
                putExtra("connectionConfig", args?.get("connectionConfig") as? String ?: "")
                putExtra("rulesJson", args?.get("rulesJson") as? String ?: "")
                putExtra("exclusionsJson", args?.get("exclusionsJson") as? String ?: "[]")
            })
        }

        fun stop(context: Context) {
            instance?.tearDown()
        }

        fun updateRules(rulesJson: String, exclusionsJson: String): String {
            val bridge = instance?.tunnelBridge
            return bridge?.updateRules(rulesJson, exclusionsJson)
                ?: "no active tunnel"
        }
    }

    private var tunInterface: ParcelFileDescriptor? = null
    private var tunnelBridge: TunnelBridge? = null
    private val scope = CoroutineScope(Dispatchers.IO + Job())
    private val mainHandler = Handler(Looper.getMainLooper())
    @Volatile private var tornDown = false

    private var relayId: String = ""
    private var relayHost: String = ""
    private var relayPort: Int = 443
    private var relayDisplayName: String = ""
    private var connectionConfig: String = ""
    private var rulesJson: String = ""
    private var exclusionsJson: String = "[]"

    override fun onCreate() {
        super.onCreate()
        instance = this
        tornDown = false
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_CONNECT) {
            relayId = intent.getStringExtra("id") ?: ""
            relayHost = intent.getStringExtra("host") ?: ""
            relayPort = intent.getIntExtra("port", 443)
            relayDisplayName = intent.getStringExtra("displayName") ?: ""
            connectionConfig = intent.getStringExtra("connectionConfig") ?: ""
            rulesJson = intent.getStringExtra("rulesJson") ?: ""
            exclusionsJson = intent.getStringExtra("exclusionsJson") ?: "[]"

            Log.i(TAG, "connect relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length}")
            ConnectLogger.log(this, "onStartCommand relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length} rulesLen=${rulesJson.length}")
            startForeground(NOTIFICATION_ID, buildNotification("Подключение…"))
            emit("connecting")
            scope.launch { establishTunnel() }
        }
        return START_STICKY
    }

    private fun buildNotification(status: String): Notification {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            val channel = NotificationChannel(
                NOTIFICATION_CHANNEL_ID,
                "StreamPass",
                NotificationManager.IMPORTANCE_LOW,
            ).apply { description = "Статус соединения StreamPass" }
            manager.createNotificationChannel(channel)
        }

        return NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
            .setContentTitle("StreamPass")
            .setContentText(status)
            .setSmallIcon(android.R.drawable.stat_sys_download_done) // заменить на брендовую иконку
            .setOngoing(true)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    private fun updateNotification(status: String) {
        val manager = getSystemService(NotificationManager::class.java)
        manager.notify(NOTIFICATION_ID, buildNotification(status))
    }

    private suspend fun establishTunnel() {
        try {
            if (tornDown) return
            if (relayHost.isEmpty()) {
                throw IllegalStateException("No relay host provided — was GET /servers called first?")
            }
            ConnectLogger.log(this, "connect-flow=v2-prepare-first build=0.1.1+10 protectfix")
            ConnectLogger.log(this, "establishTunnel: validating connection_config")
            if (connectionConfig.isBlank()) {
                throw IllegalStateException("connection_config is empty — relay misconfigured in backend")
            }
            if (!connectionConfig.startsWith("hysteria2://") && !connectionConfig.startsWith("hy2://")) {
                throw IllegalStateException("connection_config must be hysteria2:// URI, got: ${connectionConfig.take(32)}…")
            }

            val bridge = TunnelBridge(this) { event, relay, pingMs, error ->
                ConnectLogger.log(this@StreamPassVpnService, "tunnel event=$event relay=$relay error=$error pingMs=$pingMs")
                Log.i(TAG, "tunnel event=$event relay=$relay error=$error")
                emit(event, relay = relay ?: relayDisplayName.ifEmpty { relayHost }, pingMs = pingMs, error = error)
                if (event == "error") {
                    Handler(Looper.getMainLooper()).post { tearDown() }
                }
            }
            tunnelBridge = bridge

            // Protect underlay sockets BEFORE PrepareRelay so QUIC survives TUN default route.
            bridge.setSocketProtector { fd ->
                val ok = protect(fd)
                ConnectLogger.log(this@StreamPassVpnService, "protect(fd=$fd)=$ok")
                ok
            }

            // Hysteria handshake MUST complete before TUN default route is added,
            // otherwise QUIC packets to the relay loop into the empty interface.
            ConnectLogger.log(this, "PrepareRelay before TUN (relay=$relayHost:$relayPort)")
            val prepareErr = bridge.prepareRelay(relayHost, relayPort, connectionConfig)
            if (tornDown) return
            if (prepareErr != null) {
                throw IllegalStateException(prepareErr)
            }
            ConnectLogger.log(this, "PrepareRelay OK, establishing TUN")

            if (tornDown) {
                bridge.stopTunnel()
                return
            }

            tunInterface = Builder()
                .setSession("StreamPass")
                // /30 gives sing-tun system stack a second address in-prefix (required).
                .addAddress("10.10.0.2", 30)
                .addDnsServer("1.1.1.1")
                .addDnsServer("1.0.0.1")
                .addRoute("0.0.0.0", 0)
                .setMtu(1400)
                .establish()

            val fd = tunInterface?.fd
                ?: throw IllegalStateException("VPN interface could not be established")
            ConnectLogger.log(this, "TUN established fd=$fd mtu=1400")

            if (tornDown) {
                tunInterface?.close()
                tunInterface = null
                bridge.stopTunnel()
                return
            }

            bridge.startTunnel(fd, relayHost, relayPort, connectionConfig, rulesJson, exclusionsJson)
        } catch (e: Exception) {
            if (tornDown) return
            Log.e(TAG, "establishTunnel failed", e)
            ConnectLogger.log(this, "establishTunnel failed: ${e.message}")
            emit("error", error = e.message ?: "unknown error")
            tearDown()
        }
    }

    private fun releaseResources() {
        tunnelBridge?.stopTunnel()
        tunnelBridge?.clearSocketProtector()
        tunnelBridge = null
        tunInterface?.close()
        tunInterface = null
    }

    private fun tearDown() {
        if (tornDown) return
        tornDown = true
        ConnectLogger.log(this, "tearDown")
        scope.launch {
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "releaseResources failed", t)
                ConnectLogger.log(this@StreamPassVpnService, "releaseResources failed: ${t.message}")
            }
            mainHandler.post {
                emit("disconnected")
                stopForeground(STOP_FOREGROUND_REMOVE)
                stopSelf()
            }
        }
    }

    override fun onDestroy() {
        // Never call stopSelf() from onDestroy — that crashes the process
        // when Android tears down the service (e.g. after APK update).
        ConnectLogger.log(this, "onDestroy")
        if (!tornDown) {
            tornDown = true
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "onDestroy releaseResources failed", t)
            }
        }
        instance = null
        super.onDestroy()
    }

    override fun onRevoke() {
        // System revoked VPN permission (e.g. another VPN app took over).
        tearDown()
        super.onRevoke()
    }

    private fun emit(event: String, relay: String? = null, pingMs: Int? = null, error: String? = null) {
        mainHandler.post {
            val payload = mutableMapOf<String, Any?>("event" to event)
            relay?.let { payload["relay"] = it }
            pingMs?.let { payload["pingMs"] = it }
            error?.let { payload["error"] = it }
            try {
                eventSink?.success(payload)
            } catch (t: Throwable) {
                Log.e(TAG, "eventSink failed for event=$event", t)
            }

            val statusText = when (event) {
                "connecting" -> "Подключение…"
                "connected" -> "Подключено${relay?.let { " · $it" } ?: ""}"
                "error" -> "Ошибка соединения"
                else -> "Отключено"
            }
            if (event != "disconnected") updateNotification(statusText)
        }
    }
}