package com.streampass.app

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.net.VpnService
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.os.ParcelFileDescriptor
import android.util.Log
import androidx.core.app.NotificationCompat
import io.flutter.plugin.common.EventChannel
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

// import streampasscore.Streampasscore  // <- generated by `gomobile bind`
// See go_core/README.md for how this AAR is produced from the shared
// Go core (Decision Engine + Rule Engine + Hysteria2 client).

class StreamPassVpnService : VpnService() {

    companion object {
        private const val TAG = "StreamPassVpn"
        var eventSink: EventChannel.EventSink? = null
        private var instance: StreamPassVpnService? = null

        @Volatile
        var lastEvent: String = "disconnected"
        @Volatile
        var lastRelay: String? = null
        @Volatile
        var lastPingMs: Int? = null
        @Volatile
        var lastError: String? = null

        private const val ACTION_CONNECT = "com.streampass.app.CONNECT"
        private const val ACTION_DISCONNECT = "com.streampass.app.DISCONNECT"
        private const val NOTIFICATION_CHANNEL_ID = "streampass_vpn_status"
        private const val NOTIFICATION_ID = 1

        fun start(context: Context, args: Map<*, *>?) {
            ConnectLogger.log(context, "VpnService.start id=${args?.get("id")} host=${args?.get("host")}")
            val intent = Intent(context, StreamPassVpnService::class.java).apply {
                action = ACTION_CONNECT
                putExtra("id", args?.get("id") as? String ?: "")
                putExtra("host", args?.get("host") as? String ?: "")
                putExtra("port", (args?.get("port") as? Int) ?: 443)
                putExtra("displayName", args?.get("displayName") as? String ?: "")
                putExtra("connectionConfig", args?.get("connectionConfig") as? String ?: "")
                putExtra("rulesJson", args?.get("rulesJson") as? String ?: "")
                putExtra("exclusionsJson", args?.get("exclusionsJson") as? String ?: "[]")
                putExtra("bypassPackagesJson", args?.get("bypassPackagesJson") as? String ?: "[]")
                putExtra("networkMode", args?.get("networkMode") as? String ?: "split")
                putExtra("mtu", (args?.get("mtu") as? Int) ?: 1400)
                putExtra("blockUdp443", (args?.get("blockUdp443") as? Boolean) ?: false)
                putExtra("optionsJson", args?.get("optionsJson") as? String ?: "")
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.startForegroundService(intent)
            } else {
                context.startService(intent)
            }
        }

        fun stop(context: Context) {
            val svc = instance
            if (svc != null) {
                svc.tearDown()
            } else {
                context.startService(Intent(context, StreamPassVpnService::class.java).apply {
                    action = ACTION_DISCONNECT
                })
            }
        }

        fun updateRules(rulesJson: String, exclusionsJson: String): String {
            val bridge = instance?.tunnelBridge
            return bridge?.updateRules(rulesJson, exclusionsJson)
                ?: "no active tunnel"
        }

        /** Snapshot for Flutter MethodChannel getStatus (AUDIT-003 BUG-004). */
        fun statusSnapshot(): Map<String, Any?> = mapOf(
            "event" to lastEvent,
            "relay" to lastRelay,
            "pingMs" to lastPingMs,
            "error" to lastError,
            "active" to (instance != null && lastEvent == "connected"),
        )
    }

    private var tunInterface: ParcelFileDescriptor? = null
    private var tunnelBridge: TunnelBridge? = null
    private val scope = CoroutineScope(Dispatchers.IO + Job())
    private val mainHandler = Handler(Looper.getMainLooper())
    private val teardownLock = Any()
    @Volatile private var tornDown = false

    private var relayId: String = ""
    private var relayHost: String = ""
    private var relayPort: Int = 443
    private var relayDisplayName: String = ""
    private var connectionConfig: String = ""
    private var rulesJson: String = ""
    private var exclusionsJson: String = "[]"
    private var bypassPackagesJson: String = "[]"
    private var networkMode: String = "split"
    private var mtu: Int = 1400
    private var blockUdp443: Boolean = false
    private var optionsJson: String = ""

    override fun onCreate() {
        super.onCreate()
        instance = this
        tornDown = false
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_DISCONNECT) {
            tearDown()
            return START_NOT_STICKY
        }
        if (intent?.action == ACTION_CONNECT) {
            synchronized(teardownLock) { tornDown = false }
            relayId = intent.getStringExtra("id") ?: ""
            relayHost = intent.getStringExtra("host") ?: ""
            relayPort = intent.getIntExtra("port", 443)
            relayDisplayName = intent.getStringExtra("displayName") ?: ""
            connectionConfig = intent.getStringExtra("connectionConfig") ?: ""
            rulesJson = intent.getStringExtra("rulesJson") ?: ""
            exclusionsJson = intent.getStringExtra("exclusionsJson") ?: "[]"
            bypassPackagesJson = intent.getStringExtra("bypassPackagesJson") ?: "[]"
            networkMode = intent.getStringExtra("networkMode") ?: "split"
            mtu = intent.getIntExtra("mtu", 1400).coerceIn(1200, 1500)
            blockUdp443 = intent.getBooleanExtra("blockUdp443", false)
            optionsJson = intent.getStringExtra("optionsJson") ?: ""
            if (optionsJson.isBlank()) {
                // Build options for Go StartTunnel (networkMode / mtu / blockUdp443).
                val block = blockUdp443 || networkMode == "tcp_only"
                optionsJson =
                    """{"networkMode":"$networkMode","mtu":$mtu,"blockUdp443":$block}"""
            }

            Log.i(TAG, "connect relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length}")
            ConnectLogger.log(
                this,
                "onStartCommand relayId=$relayId host=$relayHost port=$relayPort configLen=${connectionConfig.length} rulesLen=${rulesJson.length} networkMode=$networkMode mtu=$mtu blockUdp443=$blockUdp443",
            )
            startForeground(NOTIFICATION_ID, buildNotification("Подключение…"))
            emit("connecting")
            scope.launch { establishTunnel() }
        }
        return START_STICKY
    }

    private fun buildNotification(status: String): Notification {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            val channel = NotificationChannel(
                NOTIFICATION_CHANNEL_ID,
                "StreamPass",
                NotificationManager.IMPORTANCE_LOW,
            ).apply { description = "Статус соединения StreamPass" }
            manager.createNotificationChannel(channel)
        }

        return NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
            .setContentTitle("StreamPass")
            .setContentText(status)
            .setSmallIcon(android.R.drawable.stat_sys_download_done) // заменить на брендовую иконку
            .setOngoing(true)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    private fun updateNotification(status: String) {
        val manager = getSystemService(NotificationManager::class.java)
        manager.notify(NOTIFICATION_ID, buildNotification(status))
    }

    private suspend fun establishTunnel() {
        try {
            if (tornDown) return
            if (relayHost.isEmpty()) {
                throw IllegalStateException("No relay host provided — was GET /servers called first?")
            }
            ConnectLogger.log(this, "connect-flow=v2-prepare-first build=0.1.1+33 routing-policy-v1")
            ConnectLogger.log(this, "establishTunnel: validating connection_config")
            if (connectionConfig.isBlank()) {
                throw IllegalStateException("connection_config is empty — relay misconfigured in backend")
            }
            if (!connectionConfig.startsWith("hysteria2://") && !connectionConfig.startsWith("hy2://")) {
                throw IllegalStateException("connection_config must be hysteria2:// URI, got: ${connectionConfig.take(32)}…")
            }

            val bridge = TunnelBridge(this) { event, relay, pingMs, error ->
                ConnectLogger.log(this@StreamPassVpnService, "tunnel event=$event relay=$relay error=$error pingMs=$pingMs")
                Log.i(TAG, "tunnel event=$event relay=$relay error=$error")
                emit(event, relay = relay ?: relayDisplayName.ifEmpty { relayHost }, pingMs = pingMs, error = error)
                if (event == "error") {
                    Handler(Looper.getMainLooper()).post { tearDown() }
                }
            }
            tunnelBridge = bridge

            // Protect underlay sockets BEFORE PrepareRelay so QUIC survives TUN default route.
            bridge.setEventLogger { msg -> ConnectLogger.log(this@StreamPassVpnService, msg) }
            bridge.setSocketProtector { fd ->
                val ok = protect(fd)
                ConnectLogger.log(this@StreamPassVpnService, "protect(fd=$fd)=$ok")
                ok
            }

            // Hysteria handshake MUST complete before TUN default route is added,
            // otherwise QUIC packets to the relay loop into the empty interface.
            ConnectLogger.log(this, "PrepareRelay before TUN (relay=$relayHost:$relayPort)")
            val prepareErr = bridge.prepareRelay(relayHost, relayPort, connectionConfig)
            if (tornDown) return
            if (prepareErr != null) {
                throw IllegalStateException(prepareErr)
            }
            ConnectLogger.log(this, "PrepareRelay OK, establishing TUN")

            if (tornDown) {
                bridge.stopTunnel()
                return
            }

            // DNS MUST be the TUN address so queries hit Go dnscache (*.ru DIRECT,
            // reverse IP→host). Yandex 77.88.8.8 is in RU exclude ranges — OS DNS
            // never entered TUN and left host= empty (all foreign → RELAY).
            val vpnBuilder = Builder()
                .setSession("StreamPass")
                .addAddress("10.10.0.1", 30)
                .addDnsServer("10.10.0.1")
                .setMtu(mtu)
            val routeInfo = VpnRouteConfigurator.apply(vpnBuilder, assets, networkMode)
            val extraBypass = parseBypassPackages(bypassPackagesJson)
            val bypassCount = VpnBypassApps.apply(vpnBuilder, packageManager, packageName, extraBypass)
            ConnectLogger.log(this, "vpn dns=10.10.0.1 (Go dnscache) networkMode=$networkMode mtu=$mtu")
            ConnectLogger.log(this, "split-tunnel mode=${routeInfo.mode} routes=${routeInfo.routeCount} ruExcludes=${routeInfo.excludeCount} appBypass=$bypassCount extraUser=${extraBypass.size}")
            tunInterface = vpnBuilder.establish()

            val fd = tunInterface?.fd
                ?: throw IllegalStateException("VPN interface could not be established")
            ConnectLogger.log(this, "TUN established fd=$fd mtu=$mtu addr=10.10.0.1/30 options=$optionsJson")
            if (tornDown) {
                tunInterface?.close()
                tunInterface = null
                bridge.stopTunnel()
                return
            }

            bridge.startTunnel(fd, relayHost, relayPort, connectionConfig, rulesJson, exclusionsJson, optionsJson)
        } catch (e: Exception) {
            if (tornDown) return
            Log.e(TAG, "establishTunnel failed", e)
            ConnectLogger.log(this, "establishTunnel failed: ${e.message}")
            emit("error", error = e.message ?: "unknown error")
            tearDown()
        }
    }

    private fun releaseResources() {
        // Close TUN first so no new packets enter Go while we tear down.
        val tun = tunInterface
        tunInterface = null
        try {
            tun?.close()
        } catch (t: Throwable) {
            Log.e(TAG, "TUN close failed", t)
        }

        val bridge = tunnelBridge
        tunnelBridge = null
        try {
            bridge?.stopTunnel()
        } catch (t: Throwable) {
            Log.e(TAG, "stopTunnel failed", t)
        }
        try {
            bridge?.clearSocketProtector()
        } catch (t: Throwable) {
            Log.e(TAG, "clearSocketProtector failed", t)
        }
    }

    private fun tearDown() {
        synchronized(teardownLock) {
            if (tornDown) return
            tornDown = true
        }
        ConnectLogger.log(this, "[vpn] stop begin")
        scope.launch {
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "releaseResources failed", t)
                ConnectLogger.log(this@StreamPassVpnService, "releaseResources failed: ${t.message}")
            }
            mainHandler.post {
                try {
                    emit("disconnected")
                    ConnectLogger.log(this@StreamPassVpnService, "[vpn] stop complete")
                    stopForeground(STOP_FOREGROUND_REMOVE)
                    // Do not stopSelf() here — on some OEMs it kills the Flutter process
                    // when the user switched to Chrome/banking apps. Service stays idle until
                    // next CONNECT or process exit.
                } catch (t: Throwable) {
                    Log.e(TAG, "tearDown finalize failed", t)
                }
            }
        }
    }

    override fun onDestroy() {
        // Never call stopSelf() from onDestroy — that crashes the process
        // when Android tears down the service (e.g. after APK update).
        ConnectLogger.log(this, "onDestroy")
        if (!tornDown) {
            tornDown = true
            try {
                releaseResources()
            } catch (t: Throwable) {
                Log.e(TAG, "onDestroy releaseResources failed", t)
            }
        }
        instance = null
        super.onDestroy()
    }

    override fun onRevoke() {
        // System revoked VPN permission (e.g. another VPN app took over).
        tearDown()
        super.onRevoke()
    }

    private fun emit(event: String, relay: String? = null, pingMs: Int? = null, error: String? = null) {
        lastEvent = event
        lastRelay = relay
        lastPingMs = pingMs
        lastError = error
        mainHandler.post {
            val payload = mutableMapOf<String, Any?>("event" to event)
            relay?.let { payload["relay"] = it }
            pingMs?.let { payload["pingMs"] = it }
            error?.let { payload["error"] = it }
            try {
                eventSink?.success(payload)
            } catch (t: Throwable) {
                Log.e(TAG, "eventSink failed for event=$event", t)
            }

            val statusText = when (event) {
                "connecting" -> "Подключение…"
                "connected" -> "Подключено${relay?.let { " · $it" } ?: ""}"
                "error" -> "Ошибка соединения"
                else -> "Отключено"
            }
            if (event != "disconnected") updateNotification(statusText)
        }
    }

    private fun parseBypassPackages(raw: String): List<String> {
        if (raw.isBlank() || raw == "[]") return emptyList()
        return try {
            val trimmed = raw.trim().removePrefix("[").removeSuffix("]")
            if (trimmed.isBlank()) return emptyList()
            trimmed.split(',')
                .map { it.trim().trim('"').trim('\'') }
                .filter { it.isNotEmpty() }
        } catch (_: Throwable) {
            emptyList()
        }
    }
}