listen: :8443

tls:
  cert: /etc/hysteria/cert.pem
  key: /etc/hysteria/key.pem

auth:
  type: password
  password: streampass-secure-auth

obfs:
  type: salamander
  salamander:
    password: streampass-relay-2024

bandwidth:
  up: 100 mbps
  down: 100 mbps
