listen: :8443

tls:
  cert: /etc/hysteria/cert.pem
  key: /etc/hysteria/key.pem

auth:
  type: password
  password: change-me-auth-local-test

obfs:
  type: salamander
  salamander:
    password: change-me-obfs-local-test

bandwidth:
  up: 100 mbps
  down: 100 mbps
