package com.streampass.app

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.content.Intent
import android.net.VpnService
import android.os.Build
import android.os.ParcelFileDescriptor
import androidx.core.app.NotificationCompat
import io.flutter.plugin.common.EventChannel
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch

// import streampasscore.Streampasscore  // <- generated by `gomobile bind`
// See go_core/README.md for how this AAR is produced from the shared
// Go core (Decision Engine + Rule Engine + Hysteria2 client).

class StreamPassVpnService : VpnService() {

    companion object {
        var eventSink: EventChannel.EventSink? = null
        private var instance: StreamPassVpnService? = null

        private const val ACTION_CONNECT = "com.streampass.app.CONNECT"
        private const val NOTIFICATION_CHANNEL_ID = "streampass_vpn_status"
        private const val NOTIFICATION_ID = 1

        fun start(context: Context) {
            context.startService(Intent(context, StreamPassVpnService::class.java).apply {
                action = ACTION_CONNECT
            })
        }

        fun stop(context: Context) {
            instance?.tearDown()
        }
    }

    private var tunInterface: ParcelFileDescriptor? = null
    private val scope = CoroutineScope(Dispatchers.IO + Job())

    override fun onCreate() {
        super.onCreate()
        instance = this
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_CONNECT) {
            startForeground(NOTIFICATION_ID, buildNotification("Подключение…"))
            emit("connecting")
            scope.launch { establishTunnel() }
        }
        return START_STICKY
    }

    private fun buildNotification(status: String): Notification {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            val channel = NotificationChannel(
                NOTIFICATION_CHANNEL_ID,
                "StreamPass",
                NotificationManager.IMPORTANCE_LOW,
            ).apply { description = "Статус соединения StreamPass" }
            manager.createNotificationChannel(channel)
        }

        return NotificationCompat.Builder(this, NOTIFICATION_CHANNEL_ID)
            .setContentTitle("StreamPass")
            .setContentText(status)
            .setSmallIcon(android.R.drawable.stat_sys_download_done) // заменить на брендовую иконку
            .setOngoing(true)
            .setPriority(NotificationCompat.PRIORITY_LOW)
            .build()
    }

    private fun updateNotification(status: String) {
        val manager = getSystemService(NotificationManager::class.java)
        manager.notify(NOTIFICATION_ID, buildNotification(status))
    }

    private suspend fun establishTunnel() {
        try {
            // 1. Pull active server + rules from backend (via ApiService equivalent
            //    on the Dart side, or directly here if the Go core owns networking).
            //    For MVP: relay endpoint comes from GET /api/v1/servers response.
            val relayHost = "212.43.159.198"
            val relayPort = 443

            // 2. Build the local TUN interface. Actual per-app/per-route rules
            //    (Domain Rules / CIDR Rules per ТЗ section 6) are NOT applied at
            //    this layer — the Go core's Decision Engine handles DIRECT vs
            //    RELAY per-connection once traffic reaches it.
            tunInterface = Builder()
                .setSession("StreamPass")
                .addAddress("10.10.0.2", 32)
                .addDnsServer("1.1.1.1")
                .addDnsServer("1.0.0.1")
                .addRoute("0.0.0.0", 0)
                .setMtu(1400)
                .establish()

            val fd = tunInterface?.fd
                ?: throw IllegalStateException("VPN interface could not be established")

            // 3. Hand the raw fd to the shared Go core. This is the actual
            //    Hysteria2 tunnel + Decision Engine entry point:
            //
            //    Streampasscore.startTunnel(
            //        fd.toLong(),
            //        relayHost,
            //        relayPort.toLong(),
            //        authPassword,
            //    )
            //
            //    startTunnel blocks / runs its own goroutines internally and
            //    calls back into Kotlin (via a gomobile callback interface)
            //    on state changes — that callback should call emit(...) below
            //    instead of this stubbed success path.

            emit("connected", relay = "Germany, Frankfurt", pingMs = 68)
        } catch (e: Exception) {
            emit("error", error = e.message ?: "unknown error")
            tearDown()
        }
    }

    private fun tearDown() {
        tunInterface?.close()
        tunInterface = null
        emit("disconnected")
        stopForeground(STOP_FOREGROUND_REMOVE)
        stopSelf()
    }

    override fun onDestroy() {
        tearDown()
        instance = null
        super.onDestroy()
    }

    override fun onRevoke() {
        // System revoked VPN permission (e.g. another VPN app took over).
        tearDown()
        super.onRevoke()
    }

    private fun emit(event: String, relay: String? = null, pingMs: Int? = null, error: String? = null) {
        val payload = mutableMapOf<String, Any?>("event" to event)
        relay?.let { payload["relay"] = it }
        pingMs?.let { payload["pingMs"] = it }
        error?.let { payload["error"] = it }
        eventSink?.success(payload)

        val statusText = when (event) {
            "connecting" -> "Подключение…"
            "connected" -> "Подключено${relay?.let { " · $it" } ?: ""}"
            "error" -> "Ошибка соединения"
            else -> "Отключено"
        }
        if (event != "disconnected") updateNotification(statusText)
    }
}
